起動スクリプトの修正、それに伴う手順の簡略化

diff --git a/unicorn/unicorn_redmine b/unicorn/unicorn_redmine
--- a/unicorn/unicorn_redmine
+++ b/unicorn/unicorn_redmine
@@ -1,60 +1,66 @@
-    #!/bin/bash
-    #
-    # unicorn_redmine Startup script for unicorn.
-    #
-    # chkconfig: - 85 15
-    # description: redmine on unicorn start/stop script.
-    #
+#!/bin/bash
 
-    set -u
-    set -e
+### BEGIN INIT INFO
+# Provides:          unicorn_redmine
+# Required-Start:    $local_fs $remote_fs $network $syslog redis-server
+# Required-Stop:     $local_fs $remote_fs $network $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: redmine
+# Description:       redmine
+### END INIT INFO
 
-    APP_NAME=redmine
-    APP_ROOT="/home/redmine/$APP_NAME"
-    CNF="$APP_ROOT/config/unicorn.rb"
-    PID="$APP_ROOT/tmp/pids/unicorn.pid"
-    ENV=production
-    UNICORN_OPTS="-c $CNF -E $ENV -D"
-    old_pid="$PID.oldbin"
+export PATH=$PATH:/usr/local/bin
 
-    cd $APP_ROOT || exit 1
+set -u
+set -e
 
-    sig () {
-            test -s "$PID" && kill -$1 `cat $PID`
-    }
-    oldsig () {
-            test -s $old_pid && kill -$1 `cat $old_pid`
-    }
+APP_NAME=redmine
+APP_ROOT="/home/redmine/$APP_NAME"
+CNF="$APP_ROOT/config/unicorn.rb"
+PID="$APP_ROOT/tmp/pids/unicorn.pid"
+ENV=production
+UNICORN_OPTS="-c $CNF -E $ENV -D"
+old_pid="$PID.oldbin"
 
-    case ${1-help} in
-    start)
-            sig 0 && echo >&2 "Already running" && exit 0
-            cd $APP_ROOT ; unicorn_rails $UNICORN_OPTS
-            ;;
-    stop)
-            sig QUIT && exit 0
-            echo >&2 "Not running"
-            ;;
-    force-stop)
-            sig TERM && exit 0
-            echo >&2 "Not running"
-            ;;
-    restart|reload)
-            sig HUP && echo reloaded OK && exit 0
-            echo >&2 "Couldn't reload, starting instead"
-            unicorn_rails $UNICORN_OPTS
-            ;;
-    upgrade)
-            sig USR2 && exit 0
-            echo >&2 "Couldn't upgrade, starting instead"
-            unicorn_rails $UNICORN_OPTS
-            ;;
-    rotate)
-            sig USR1 && echo rotated logs OK && exit 0
-            echo >&2 "Couldn't rotate logs" && exit 1
-            ;;
-    *)
-            echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
-            exit 1
-            ;;
-    esac
+cd $APP_ROOT || exit 1
+
+sig () {
+        test -s "$PID" && kill -$1 `cat $PID`
+}
+oldsig () {
+        test -s $old_pid && kill -$1 `cat $old_pid`
+}
+
+case ${1-help} in
+start)
+        sig 0 && echo >&2 "Already running" && exit 0
+        cd $APP_ROOT ; unicorn_rails $UNICORN_OPTS
+        ;;
+stop)
+        sig QUIT && exit 0
+        echo >&2 "Not running"
+        ;;
+force-stop)
+        sig TERM && exit 0
+        echo >&2 "Not running"
+        ;;
+restart|reload)
+        sig HUP && echo reloaded OK && exit 0
+        echo >&2 "Couldn't reload, starting instead"
+        unicorn_rails $UNICORN_OPTS
+        ;;
+upgrade)
+        sig USR2 && exit 0
+        echo >&2 "Couldn't upgrade, starting instead"
+        unicorn_rails $UNICORN_OPTS
+        ;;
+rotate)
+        sig USR1 && echo rotated logs OK && exit 0
+        echo >&2 "Couldn't rotate logs" && exit 1
+        ;;
+*)
+        echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
+        exit 1
+        ;;
+esac
